<?php
echo '<!DOCTYPE html>';
echo '<html lang="en">';
echo '<head>';
echo '<meta charset="UTF-8">';
echo '<meta http-equiv="X-UA-Compatible" content="IE=edge">';
echo '<meta name="viewport" content="width=device-width, initial-scale=1.0">';
echo '<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">';
echo '<title>Amrita Epidemic Management system</title>';
echo '<link rel="stylesheet" href="bgh.css">';
echo '<link rel="stylesheet" href="flip.css">';
echo '<link rel="stylesheet" href="footer.css">';
echo '<link rel="stylesheet" href="buttton.css">';
echo '<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">';
echo '<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">';
echo '<style media="screen">';
echo '@media (max-width:500px) {';
echo '.footer-menu ul{';
echo 'display: flex;';
echo 'margin-top: 10px;';
echo 'margin-bottom: 20px;';
echo '}}';
echo '.hello{';
echo 'display: inline-block;';
echo 'transition: transform 0.5s ;';
echo 'text-align: center;';
echo 'text-decoration: none;';
echo 'background-color: whitesmoke;';
echo 'font-family:cursive;';
echo 'border-radius: 20px;';
echo 'color: #336699;';
echo 'font-size: 70px;';
echo '}';
echo '.hello:hover{';
echo 'display: inline-block;';
echo '-ms-transform: scale(1.2);';
echo '-webkit-transform: scale(1.2);';
echo 'transform: scale(1.2);';
echo 'transform: all;';
echo 'background-color: #336699;';
echo 'color: whitesmoke;';
echo '}';
echo '</style>';
echo '<script>';
echo 'function f1()';
echo '{';
echo 'var dispName= prompt("Hi!, Enter your name :)");';
echo 'if (dispName != null) {';
echo 'document.getElementById("d").innerHTML = "Hello " + dispName + "  :)";';
echo '}';
echo '}';
echo '';
echo '</script>';
echo '</head>';
echo '<body style="background:#336699;overflow-x: hidden;" onload="f1()">';
echo '';
echo '<nav class="navbar navbar-expand-lg navbar-light bg-dark" >';
echo '<div class= "container-fluid" >';
echo '<h1 style="float: left;width: 80%;color: beige;"><b style="color: red;">A</b>mrita</h1>';
echo '<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">';
echo '<span class="navbar-toggler-icon"></span>';
echo '</button>';
echo '<div class="collapse navbar-collapse" id="navbarNav">';
echo '<ul class="navbar-nav" >';
echo '<li class="nav-item" >';
echo '<a class="nav-link active" aria-current="page" href="index.html" style="color: beige;">Home</a>';
echo '</li>';
echo '<li class="nav-item">';
echo '<a class="nav-link" href="#" style="color: beige;">About Us</a>';
echo '</li>';
echo '<li class="nav-item" >';
echo '<a class="nav-link" href="#contact" style="color: beige;">Contact</a>';
echo '</li>';
echo '</ul>';
echo '</div>';
echo '</div>';
echo '</nav>';
echo '<div class="container">';
echo '<img src="bgh.png" width="1530" >';
echo '<h1 style="color: red;font-family:fantasy" class="txt-head"><b>Epidemic Management Solutions</b></h1>';
echo '<div class="text-block">';
echo '<div class="wrapper">';
echo '';
echo '<p style="text-align: center;font-size: 30px;font-family:cursive" class="cont">A Initiative by Team <span style="color: red;">A</span>mrita...<br> Powerful response to the threats faced <br>in the pandemic situations.</p>';
echo '</div>';
echo '</div>';
echo '';
echo '</div>';
echo '</div>';
echo '<div>';
echo '<br><br>';
echo '<h1 style="text-align: center;"><a id="d" style="text-align: center;color: #336699;" class="hello"></a></h1>';
echo '<br><br>';
echo '<table align="center" cellpadding="30">';
echo '<tr style="width:300px;height:300px;">';
echo '<td>';
echo '<div class="flip-card">';
echo '<div class="flip-card-inner">';
echo '<div class="flip-card-front">';
echo '<img src="doc.png" alt="Avatar" style="width:300px;height:300px;">';
echo '<h2 style="text-align: center;">DOCTOR/STAFF</h2>';
echo '</div>';
echo '<div class="flip-card-back">';
echo '<h1>Are you a Doctor?</h1>';
echo '<form method="GET" action="Doctor_Login.html">';
echo '<button type="submit">Visit here</button>';
echo '</form>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '</td>';
echo '<td>';
echo '<div class="flip-card">';
echo '<div class="flip-card-inner">';
echo '<div class="flip-card-front">';
echo '<img src="pat.png" alt="Avatar" style="width:300px;height:300px;">';
echo '<h2 style="text-align: center;">PATIENT</h2>';
echo '</div>';
echo '<div class="flip-card-back">';
echo '<h1>Are you a Patient?</h1> <br>';
echo '<form method="GET" action="Patient_Login.html">';
echo '<button type="submit">Visit here</button>';
echo '</form>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</td>';
echo '</tr>';
echo '<tr>';
echo '<td>';
echo '<div class="flip-card">';
echo '<div class="flip-card-inner">';
echo '<div class="flip-card-front">';
echo '<img src="adm.png" alt="Avatar" style="width:300px;height:300px;">';
echo '<h2 style="text-align: center;">ADMIN</h2>';
echo '</div>';
echo '<div class="flip-card-back">';
echo '<h1>Are you a Admin?</h1> <br>';
echo '<form method="GET" action="Admin_Login.html">';
echo '<button type="submit">Visit here</button>';
echo '</form>';
echo '';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</td>';
echo '<td>';
echo '<div class="flip-card">';
echo '<div class="flip-card-inner">';
echo '<div class="flip-card-front">';
echo '<img src="visit.png" alt="Avatar" style="width:300px;height:300px;">';
echo '<h2 style="text-align: center;">VISITOR</h2>';
echo '</div>';
echo '<div class="flip-card-back">';
echo '<h1>Are you a Visitor?</h1> <br>';
echo '<form method="GET" action="Visitor_Login.html">';
echo '<button type="submit">Visit here</button>';
echo '</form>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</td>';
echo '</tr>';
echo '</table>';
echo '<footer>';
echo '<div class="footer-content">';
echo '<h3><span style="color: red;">A</span>mrita Epidemic Management Solutions</h3>';
echo '<div class="footer-menu" style="text-align: center;">';
echo '<ul class="f-menu">';
echo '<li><a href="index.html">&emsp;&emsp;&emsp;&emsp;Home + </a></li>';
echo '<li><a href="">About + </a></li>';
echo '<li><a href="#contact">Contact</a></li>';
echo '</ul>';
echo '<p id="contact"><u>Contact :</u></p>';
echo '<ul class="f-menu">';
echo '<li style=" color:  #8f9296">ph.no : xxxxxxxxxx</li>';
echo '<li style=" color:  #8f9296">email-id : amrita@gmail.com</li>';
echo '</ul>';
echo '';
echo '';
echo '<p style=" color:  #8f9296;font-size: 14px;font-weight: normal;">&emsp;Amrita Epidemic Management Solutions &copy; 2021</p>';
echo '<ul class="socials">';
echo '<li><a href="#"><i class="fa fa-facebook"></i></a></li>';
echo '<li><a href="#"><i class="fa fa-twitter"></i></a></li>';
echo '<li><a href="#"><i class="fa fa-instagram"></i></a></li>';
echo '<li><a href="#"><i class="fa fa-youtube"></i></a></li>';
echo '</ul>';
echo '</div>';
echo '</div>';
echo '</footer>';
echo '';
echo '</body>';
echo '</html>';
?>